# Generated by Django 6.0.7 on 2026-08-07 09:49

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, upload_to='users/')),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'M'), ('Ж', 'Ж')], default='M', max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)])),
                ('city', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
