# Generated by Django 6.0.7 on 2026-08-05 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketbook',
            name='card_number',
            field=models.CharField(default=0, max_length=16, validators=[django.core.validators.RegexValidator(message='Номер карты должен состоять ровно из 16 цифр.', regex='^\\d{16}$')]),
            preserve_default=False,
        ),
    ]
