# Generated by Django 6.0.7 on 2026-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='CineBoard/')),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('просмотрено', 'просмотрено'), ('в планах', 'в планах'), ('заброшено', 'заброшено')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CinemaForm',
        ),
    ]
