# Generated by Django 6.0.7 on 2026-08-14 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0002_cinemamodel_delete_cinemaform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cinemamodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cinemamodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cinemamodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cinemamodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='age_limit',
            field=models.CharField(default='16+', max_length=10),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='country',
            field=models.CharField(default='США', max_length=100),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='director',
            field=models.CharField(default='Режиссер', max_length=100),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='duration',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='release_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AlterField(
            model_name='cinemamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinemamodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cinemamodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CineBoard.cinemamodel')),
            ],
        ),
        migrations.AddField(
            model_name='cinemamodel',
            name='genres',
            field=models.ManyToManyField(to='CineBoard.genre'),
        ),
        migrations.CreateModel(
            name='VIPReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CineBoard.cinemamodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CastomUser',
        ),
    ]
