# Generated by Django 6.0.7 on 2026-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='book/')),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('url_book', models.URLField(blank=True)),
                ('type', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
    ]
