# Generated by Django 6.0.7 on 2026-07-31 10:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(null=True, to='horse_tour.categoryhorse'),
        ),
        migrations.CreateModel(
            name='CommentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.location')),
            ],
        ),
    ]
