# Generated by Django 6.0.7 on 2026-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0002_categoryhorse_location_categories_commentlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, to='horse_tour.categoryhorse'),
        ),
    ]
